version: '3.7'

services:
   db:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: kh0ngbjet
      MYSQL_DATABASE: db_ef_example
    ports:
      - "3306:3306"
   admin:    
    image: adminer    
    ports:      
      - "8080:8080"
   back-end:
    image: code_first:test
    container_name: ef_code_first
    build:
        dockerfile: Backend.Dockerfile
        context: .
    restart: unless-stopped
    ports:
        - "8080:5000"